### ISSUE TITLE
Huffman Coding

### ISSUE THREAD

**Issue by mgoadric** [mgoadric/cs2mulch#11]
Can we put chits on cards, and do Huffman Encoding? 

https://en.wikipedia.org/wiki/Huffman_coding

The letter on the chit would have the frequency of the number on the Acorn card. 

How would we represent the intermediate nodes? Face-down cards like in skip-list?

**Comment by qsebring3930** [comment]
I think Huffman encoding is possible with chits and acorns, will chits cover special characters and spaces or for the sake of simplicity just letters? For intermediate nodes, I think face down cards with implicit values would work. Or possibly using the numbered cards from menagerie as index numbers for storing the intermediate node values on a separate piece of paper and limiting the input string to 8 letters would also work (albeit a little more hassle for someone using the cards).

**Comment by mgoadric** [comment]
There are 26 chits, one for each letter, one side red, the other black. So I'm thinking the student shuffles and deals out 8 cards, sorts them, then takes 8 chits randomly and puts one on each card. The card # is the frequency of that letter. Then you slowly make a tree, creating the intermediate nodes and resorting the list as you go.
