### ISSUE TITLE
Skip List

### ISSUE THREAD

**Issue by mgoadric** [mgoadric/cs2mulch#6]
A Skip List can be created using the Acorn Cards.

https://en.wikipedia.org/wiki/Skip_list

**Comment by qsebring3930** [comment]
I'm finding this harder to interpret than other issues, first the randomness aspect. Do you want to introduce coins or dice to the deck? I don't feel there is a way to randomly decide what level an acorn card would be inserted into that works without just letting the end user pick what level they want. Additionally, cards have to stretch across multiple levels and I'm not sure how to interpret that without doubling/tripling cards on top of each other. I could possibly wait until chits are added and use chits like level counters?

**Comment by mgoadric** [comment]
this image is most in line with what I think we can do with the cards. All the stacked levels can be face-down cards.

![image](https://github.com/mgoadric/cs2mulch/assets/1328659/31877b4b-18d2-41e0-b8e4-e63b3a0f2a1c)
