### ISSUE TITLE
Binary Tree Rotations

### ISSUE THREAD

**Issue by mgoadric** [mgoadric/cs2mulch#7]
Rotations are an essential step of tree balancing algorithms, and should be demonstrated.

https://en.wikipedia.org/wiki/Tree_rotation#:~:text=In%20discrete%20mathematics%2C%20tree%20rotation,tree%20and%20one%20node%20down.

**Comment by qsebring3930** [comment]
https://mgoadric.github.io/cs2mulch/tree/rotation/ ?

**Comment by mgoadric** [comment]
I must have missed that when I was making issues, thanks!
